name: drop
version: "1.0-SNAPSHOT"
author: Artin Hackers Team
main: cz.artin.hackers.Drop
commands:
  startMatch:
    description: Starts the match
  endMatch:
    description: Ends the match
  showScore:
    description: Shows the current score
  buildArena:
    description: Build arena
  setPortalExit:
    description: Sets current coordinates as main portal exit
  spawnDummies:
    description: Spawns dummies around the player
  buildObelisk:
    description: Builds an obelisk which allows player to teleport to his current portal exit
  sethometown:
    description: create hometown
  speedHack:
    description: uiogsd
