name: drop
version: "1.0-SNAPSHOT"
author: Artin Hackers Team
main: cz.artin.hackers.Drop
commands:
  spawnChicken:
    description: Spawns a chicken near the player
  spawnRabbit:
    description: Spawns a chicken near the player
  spawnWolf:
    description: Spawns a chicken near the player
