name: drop
version: "1.0-SNAPSHOT"
author: Artin Hackers Team
main: cz.artin.hackers.Drop
api-version: 1.15
commands:
  createLobby:
    description: Create a lobby and bring all the online players
  startMatch:
    description: Start the match
  endMatch:
    description: End the match
  showScore:
    description: Show the current score
  clearArea:
    description: Clear area around the player
  dropInventory:
    description: Remove all items from thw player's inventory
  setLevel:
    description: Set specific level to the player
  getRandomBuff:
    description: get random buff
  spawnchicken:
    description: spawn chicken
  createwall:
    description: create wall.