name: drop
version: "1.0-SNAPSHOT"
author: Artin Hackers Team
main: cz.artin.hackers.Drop
commands:
  setModeDeveloper:
    description: Sets creative mode, day and disables day-night cycle
  setModeNormal:
    description: Sets survival mode, and enables day-night cycle
  spawnChicken:
    description: Spawns a chicken near the player
  spawnDummies:
    description: Spawns dummies around the player
  spawnRabbit:
    description: Spawns a chicken near the player
  spawnWolf:
    description: Spawns a chicken near the player
