name: drop
version: "1.0-SNAPSHOT"
author: Artin Hackers Team
main: cz.artin.hackers.Drop
commands:
  setModeDeveloper:
    description: Sets creative mode, day and disables day-night cycle
  setModeNormal:
    description: Sets survival mode, and enables day-night cycle
  setPortalExit:
    description: Sets current coordinates as main portal exit
  spawnChicken:
    description: Spawns a chicken near the player
  spawnDummies:
    description: Spawns dummies around the player
  teleport:
    description: Teleports player to main portal exit
