name: drop
version: "1.0-SNAPSHOT"
author: Artin Hackers Team
main: cz.artin.hackers.Drop
commands:
  createLobby:
    description: Create a lobby and bring all the online players
  startMatch:
    description: Start the match
  endMatch:
    description: End the match
  showScore:
    description: Show the current score
  debugClearArea:
    description: Debug - Clear area around the player
  debugDropInventory:
    description: Debug - Remove all items from thw player's inventory
  debugSetLevel:
    description: Debug - Set specific level to the player
