name: drop
version: "1.0-SNAPSHOT"
author: Artin Hackers Team
main: cz.artin.hackers.Drop
commands:
  startMatch:
    description: Start the match
  endMatch:
    description: End the match
  showScore:
    description: Show the current score
  debugClearArea:
    description: Debug - Clear area around the player
  debugBuildLobby:
    description: Debug - Build lobby and bring the players
  debugDropInventory:
    description: Debug - Remove all items from player inventory
  debugSetLevel:
    description: Debug - Set specific levet to the player
